services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    env_file:
      - .env
    command: ["gunicorn", "schoolapps.wsgi:application", "--bind", "0.0.0.0:8000", "-c", "gunicorn.conf.py"]
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"] # debug用
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    # ports: # debug用
    #   - "8000:8000" # debug用
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    image: nginx:1.29
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_data:/usr/share/nginx/html/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  static_data:
